### PR TITLE
feat/EP-22_CALENDAR_EXPORT

### PR DESCRIPTION
**Pull request by YanBurton**
## Description

JIRA: https://champlainsaintlambert.atlassian.net/jira/software/projects/EP/boards/54/backlog?selectedIssue=EP-22
As a user I want to export all the events in my calendar to a .ics file for external use.

## Changes

- Added button to export calendar to csv file

## Screenshots

image
image
image
image

### CODE REVIEW

**Review by Carstal — COMMENTED** [review]
Why are we exporting to csv instead of ics?

**Comment by YanBurton** [comment]
> 

Mostly because csv files are simpler, as they are values separated by commas. Most calendar application work with either csv or ics.

**Review by Carstal — COMMENTED** [review]
Can you export an empty csv file?

**Comment by YanBurton** [comment]
Not anymore!

**Review by Carstal — APPROVED** [review]
Thank you for making changes and answering my questions.

**Pull request merged**
